name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - solc-version: "0.5.0"
          - solc-version: "0.5.17"
          - solc-version: "0.6.0"
          - solc-version: "0.6.12"
          - solc-version: "0.7.0"
          - solc-version: "0.7.6"
          - solc-version: "0.8.0"
          - solc-version: "0.8.29"

    steps:
    - name: Set up NodeJS
      uses: actions/setup-node@v4
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      env:
        SOLC_VERSION: ${{ matrix.solc-version }}
      run: make
